### ISSUE TITLE
Configuration for Nodejs app ?

### ISSUE THREAD

**Issue by daslicht** [Microsoft/vscode-webkit-debug#46]
Hello,
is there somewhere an example how to configure chomelogger in conjunction with a node app?

**Comment by roblourens** [comment]
VS Code can debug a node app already without this extension - if you want to debug a node server and an app in Chrome at the same time, you can do that with two instances of VS Code. Does that answer your question?

**Comment by daslicht** [comment]
yeah somehow, I haven't managed to setup the launch yet
